/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.onlinerestaurant.client.presentation;

import co.unicauca.onlinerestaurant.commons.domain.Restaurant;
import java.util.List;

/**
 *
 * @author Santiago Acuña
 */
public class GUIListRestaurants extends javax.swing.JInternalFrame {

    List<Restaurant> restaurants;

    /**
     * Creates new form GUIListRestaurants
     *
     * @param restaurants Lista de restaurante
     */
    public GUIListRestaurants(List<Restaurant> restaurants) {
        initComponents();
        this.restaurants = restaurants;
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnNorte = new javax.swing.JPanel();
        jPnSur = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPnCentro = new javax.swing.JPanel();
        jPnlCentroNorte = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLblRestaurantNombre = new javax.swing.JLabel();
        jLblRestaurantDireccion = new javax.swing.JLabel();
        JLblRestaurantTelefono = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblRestaurants = new javax.swing.JTable();

        jPnNorte.setBackground(new java.awt.Color(54, 33, 88));
        jPnNorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPnNorte.setPreferredSize(new java.awt.Dimension(450, 50));

        javax.swing.GroupLayout jPnNorteLayout = new javax.swing.GroupLayout(jPnNorte);
        jPnNorte.setLayout(jPnNorteLayout);
        jPnNorteLayout.setHorizontalGroup(
            jPnNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        jPnNorteLayout.setVerticalGroup(
            jPnNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        getContentPane().add(jPnNorte, java.awt.BorderLayout.PAGE_START);

        jPnSur.setBackground(new java.awt.Color(54, 33, 88));
        jPnSur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPnSur.setPreferredSize(new java.awt.Dimension(450, 50));

        jButton1.setText("Seleccionar Restaurante");
        jPnSur.add(jButton1);

        getContentPane().add(jPnSur, java.awt.BorderLayout.PAGE_END);

        jPnCentro.setLayout(new java.awt.BorderLayout());

        jPnlCentroNorte.setBackground(new java.awt.Color(255, 255, 255));
        jPnlCentroNorte.setPreferredSize(new java.awt.Dimension(711, 200));
        jPnlCentroNorte.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 168));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPnlCentroNorte.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLblRestaurantNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblRestaurantNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLblRestaurantNombre.setText("Nombre");

        jLblRestaurantDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblRestaurantDireccion.setForeground(new java.awt.Color(0, 0, 0));
        jLblRestaurantDireccion.setText("Direccion");

        JLblRestaurantTelefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLblRestaurantTelefono.setForeground(new java.awt.Color(0, 0, 0));
        JLblRestaurantTelefono.setText("Telefono");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblRestaurantNombre)
                    .addComponent(JLblRestaurantTelefono)
                    .addComponent(jLblRestaurantDireccion))
                .addGap(0, 311, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLblRestaurantNombre)
                .addGap(40, 40, 40)
                .addComponent(jLblRestaurantDireccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(JLblRestaurantTelefono)
                .addGap(21, 21, 21))
        );

        jPnlCentroNorte.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPnCentro.add(jPnlCentroNorte, java.awt.BorderLayout.PAGE_START);

        jTblRestaurants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Direccion", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblRestaurants.setRowHeight(30);
        jScrollPane1.setViewportView(jTblRestaurants);

        jPnCentro.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPnCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLblRestaurantTelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblRestaurantDireccion;
    private javax.swing.JLabel jLblRestaurantNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnCentro;
    private javax.swing.JPanel jPnNorte;
    private javax.swing.JPanel jPnSur;
    private javax.swing.JPanel jPnlCentroNorte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblRestaurants;
    // End of variables declaration//GEN-END:variables

    private void mostrarTabla() {
        String dataTable[][] = new String[restaurants.size()][3];

        for (int i = 0; i < restaurants.size(); i++) {
            dataTable[i][0] = restaurants.get(i).getNameRestaurant();
            dataTable[i][1] = restaurants.get(i).getAddressRestaurant();
            dataTable[i][2] = restaurants.get(i).getPhone();
        }

        jTblRestaurants.setModel(new javax.swing.table.DefaultTableModel(
                dataTable, new String[]{"Nombre", "Direccion", "Telefono"}));
    }
}
