/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.onlinerestaurant.client.presentation;

/**
 *
 * @author Santiago Acuña
 */
public class GUIMenuFoodDishes extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIMenuFoodDishes
     */
    public GUIMenuFoodDishes() {
        initComponents();
        setMaximizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setClosable(true);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(54, 33, 88));

        jMenu1.setBackground(new java.awt.Color(54, 33, 88));
        jMenu1.setForeground(new java.awt.Color(204, 204, 204));
        jMenu1.setText("Dishes");

        jMenuItem1.setBackground(new java.awt.Color(54, 33, 88));
        jMenuItem1.setForeground(new java.awt.Color(204, 204, 204));
        jMenuItem1.setText("Create Dishe");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(54, 33, 88));
        jMenuItem2.setForeground(new java.awt.Color(204, 204, 204));
        jMenuItem2.setText("Find Dishe");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(54, 33, 88));
        jMenuItem3.setForeground(new java.awt.Color(204, 204, 204));
        jMenuItem3.setText("Update Dishe");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setBackground(new java.awt.Color(54, 33, 88));
        jMenuItem4.setForeground(new java.awt.Color(204, 204, 204));
        jMenuItem4.setText("Delete Dishe");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
