/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.onlinerestaurant.client.presentation;

import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Santiago Acuña
 */
public class GUIMenuAdmin extends javax.swing.JFrame {

    private boolean state = false;
    private int x = 0;
    private int y = 0;

    public GUIMenuAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        addIcon(jLbHomePageIcono, "src/main/java/resources/home.png");
        addIcon(jLbRestaurantIcon, "src/main/java/resources/restaurant.png");
        addIcon(jLbMenusIcon, "src/main/java/resources/restaurantMenu.png");
        addIcon(jLbFoodDishesIcon, "src/main/java/resources/foodDishes.png");
        addIcon(jLbDrinksIcon, "src/main/java/resources/drinks.png");
        addIcon(jLbCustomersIcon, "src/main/java/resources/customers.png");
        addIcon(jLbUsersIcon, "src/main/java/resources/users.png");
        addIcon(jLbAccountingIcon, "src/main/java/resources/accounting.png");
        addIcon(jLbUserPhoto, "src/main/java/resources/userPhoto.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlBg = new javax.swing.JPanel();
        jPnlSide = new javax.swing.JPanel();
        jPnlHomePage = new javax.swing.JPanel();
        jLbHomePageIcono = new javax.swing.JLabel();
        jLbHomePage = new javax.swing.JLabel();
        jPnlDrinks = new javax.swing.JPanel();
        jLbDrinksIcon = new javax.swing.JLabel();
        jLbDrinks = new javax.swing.JLabel();
        jPnlMenus = new javax.swing.JPanel();
        jLbMenusIcon = new javax.swing.JLabel();
        jLbMenus = new javax.swing.JLabel();
        jPnlRestaurant = new javax.swing.JPanel();
        jLbRestaurantIcon = new javax.swing.JLabel();
        jLbRestaurant = new javax.swing.JLabel();
        jPnlFoodDishes = new javax.swing.JPanel();
        jLbFoodDishesIcon = new javax.swing.JLabel();
        jLbFoodDishes = new javax.swing.JLabel();
        jPnlAccounting = new javax.swing.JPanel();
        jLbAccountingIcon = new javax.swing.JLabel();
        jLbAccounting = new javax.swing.JLabel();
        jPnlUsers = new javax.swing.JPanel();
        jLbUsersIcon = new javax.swing.JLabel();
        jLbUsers = new javax.swing.JLabel();
        jPnlCustomers = new javax.swing.JPanel();
        jLbCustomersIcon = new javax.swing.JLabel();
        jLbCurtomers = new javax.swing.JLabel();
        jLbLogOut = new javax.swing.JLabel();
        jLbUserName = new javax.swing.JLabel();
        jLbUserPhoto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPnlCMH = new javax.swing.JPanel();
        jLbMaxMin = new javax.swing.JLabel();
        jLbHide = new javax.swing.JLabel();
        jLbClose1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPnlBg.setBackground(new java.awt.Color(255, 255, 255));
        jPnlBg.setLayout(new java.awt.BorderLayout());

        jPnlSide.setBackground(new java.awt.Color(54, 33, 88));
        jPnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPnlHomePage.setBackground(new java.awt.Color(85, 65, 118));

        jLbHomePageIcono.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbHomePage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbHomePage.setForeground(new java.awt.Color(204, 204, 204));
        jLbHomePage.setText("Home page");

        javax.swing.GroupLayout jPnlHomePageLayout = new javax.swing.GroupLayout(jPnlHomePage);
        jPnlHomePage.setLayout(jPnlHomePageLayout);
        jPnlHomePageLayout.setHorizontalGroup(
            jPnlHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlHomePageLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbHomePageIcono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnlHomePageLayout.setVerticalGroup(
            jPnlHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbHomePage)
                    .addComponent(jLbHomePageIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(jPnlHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 280, 40));

        jPnlDrinks.setBackground(new java.awt.Color(64, 43, 100));

        jLbDrinksIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbDrinks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbDrinks.setForeground(new java.awt.Color(204, 204, 204));
        jLbDrinks.setText("Drinks");

        javax.swing.GroupLayout jPnlDrinksLayout = new javax.swing.GroupLayout(jPnlDrinks);
        jPnlDrinks.setLayout(jPnlDrinksLayout);
        jPnlDrinksLayout.setHorizontalGroup(
            jPnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDrinksLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbDrinksIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnlDrinksLayout.setVerticalGroup(
            jPnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlDrinksLayout.createSequentialGroup()
                .addGroup(jPnlDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbDrinksIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlDrinksLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbDrinks)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(jPnlDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 40));

        jPnlMenus.setBackground(new java.awt.Color(64, 43, 100));

        jLbMenusIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbMenus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbMenus.setForeground(new java.awt.Color(204, 204, 204));
        jLbMenus.setText("Menus");

        javax.swing.GroupLayout jPnlMenusLayout = new javax.swing.GroupLayout(jPnlMenus);
        jPnlMenus.setLayout(jPnlMenusLayout);
        jPnlMenusLayout.setHorizontalGroup(
            jPnlMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMenusLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbMenusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbMenus, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnlMenusLayout.setVerticalGroup(
            jPnlMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMenusLayout.createSequentialGroup()
                .addGroup(jPnlMenusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbMenusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlMenusLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbMenus)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(jPnlMenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, 40));

        jPnlRestaurant.setBackground(new java.awt.Color(64, 43, 100));

        jLbRestaurantIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbRestaurant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbRestaurant.setForeground(new java.awt.Color(204, 204, 204));
        jLbRestaurant.setText("Restaurants");

        javax.swing.GroupLayout jPnlRestaurantLayout = new javax.swing.GroupLayout(jPnlRestaurant);
        jPnlRestaurant.setLayout(jPnlRestaurantLayout);
        jPnlRestaurantLayout.setHorizontalGroup(
            jPnlRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlRestaurantLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbRestaurantIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnlRestaurantLayout.setVerticalGroup(
            jPnlRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlRestaurantLayout.createSequentialGroup()
                .addGroup(jPnlRestaurantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbRestaurantIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlRestaurantLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbRestaurant)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(jPnlRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, 40));

        jPnlFoodDishes.setBackground(new java.awt.Color(64, 43, 100));

        jLbFoodDishesIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbFoodDishes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbFoodDishes.setForeground(new java.awt.Color(204, 204, 204));
        jLbFoodDishes.setText("Food dishes");

        javax.swing.GroupLayout jPnlFoodDishesLayout = new javax.swing.GroupLayout(jPnlFoodDishes);
        jPnlFoodDishes.setLayout(jPnlFoodDishesLayout);
        jPnlFoodDishesLayout.setHorizontalGroup(
            jPnlFoodDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFoodDishesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbFoodDishesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbFoodDishes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnlFoodDishesLayout.setVerticalGroup(
            jPnlFoodDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFoodDishesLayout.createSequentialGroup()
                .addGroup(jPnlFoodDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbFoodDishesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlFoodDishesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbFoodDishes)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(jPnlFoodDishes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, -1, 40));

        jPnlAccounting.setBackground(new java.awt.Color(64, 43, 100));

        jLbAccountingIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbAccounting.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbAccounting.setForeground(new java.awt.Color(204, 204, 204));
        jLbAccounting.setText("Accounting");

        javax.swing.GroupLayout jPnlAccountingLayout = new javax.swing.GroupLayout(jPnlAccounting);
        jPnlAccounting.setLayout(jPnlAccountingLayout);
        jPnlAccountingLayout.setHorizontalGroup(
            jPnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAccountingLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbAccountingIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbAccounting, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnlAccountingLayout.setVerticalGroup(
            jPnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAccountingLayout.createSequentialGroup()
                .addGroup(jPnlAccountingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbAccountingIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlAccountingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbAccounting)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(jPnlAccounting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, 40));

        jPnlUsers.setBackground(new java.awt.Color(64, 43, 100));

        jLbUsersIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbUsers.setForeground(new java.awt.Color(204, 204, 204));
        jLbUsers.setText("Users");

        javax.swing.GroupLayout jPnlUsersLayout = new javax.swing.GroupLayout(jPnlUsers);
        jPnlUsers.setLayout(jPnlUsersLayout);
        jPnlUsersLayout.setHorizontalGroup(
            jPnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUsersLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbUsersIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnlUsersLayout.setVerticalGroup(
            jPnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlUsersLayout.createSequentialGroup()
                .addGroup(jPnlUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbUsersIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlUsersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbUsers)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(jPnlUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, -1, 40));

        jPnlCustomers.setBackground(new java.awt.Color(64, 43, 100));

        jLbCustomersIcon.setPreferredSize(new java.awt.Dimension(34, 35));

        jLbCurtomers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLbCurtomers.setForeground(new java.awt.Color(204, 204, 204));
        jLbCurtomers.setText("Customers");

        javax.swing.GroupLayout jPnlCustomersLayout = new javax.swing.GroupLayout(jPnlCustomers);
        jPnlCustomers.setLayout(jPnlCustomersLayout);
        jPnlCustomersLayout.setHorizontalGroup(
            jPnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCustomersLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLbCustomersIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLbCurtomers, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPnlCustomersLayout.setVerticalGroup(
            jPnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCustomersLayout.createSequentialGroup()
                .addGroup(jPnlCustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLbCustomersIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlCustomersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLbCurtomers)))
                .addGap(21, 21, 21))
        );

        jPnlSide.add(jPnlCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, 40));

        jLbLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLbLogOut.setForeground(new java.awt.Color(204, 204, 204));
        jLbLogOut.setText("Log out");
        jPnlSide.add(jLbLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 50, -1));

        jLbUserName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLbUserName.setForeground(new java.awt.Color(204, 204, 204));
        jLbUserName.setText("User");
        jPnlSide.add(jLbUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 130, -1));
        jPnlSide.add(jLbUserPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 100));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jPnlSide.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 260, 10));

        jPnlBg.add(jPnlSide, java.awt.BorderLayout.LINE_START);

        jPnlCMH.setBackground(new java.awt.Color(122, 72, 221));
        jPnlCMH.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPnlCMHMouseDragged(evt);
            }
        });
        jPnlCMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPnlCMHMousePressed(evt);
            }
        });

        jLbMaxMin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLbMaxMin.setForeground(new java.awt.Color(255, 255, 255));
        jLbMaxMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbMaxMin.setText("[]");
        jLbMaxMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbMaxMinMouseClicked(evt);
            }
        });

        jLbHide.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLbHide.setForeground(new java.awt.Color(255, 255, 255));
        jLbHide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbHide.setText("-");
        jLbHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbHideMouseClicked(evt);
            }
        });

        jLbClose1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLbClose1.setForeground(new java.awt.Color(255, 255, 255));
        jLbClose1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbClose1.setText("X");
        jLbClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLbClose1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnlCMHLayout = new javax.swing.GroupLayout(jPnlCMH);
        jPnlCMH.setLayout(jPnlCMHLayout);
        jPnlCMHLayout.setHorizontalGroup(
            jPnlCMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlCMHLayout.createSequentialGroup()
                .addContainerGap(1014, Short.MAX_VALUE)
                .addComponent(jLbHide, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLbMaxMin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLbClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPnlCMHLayout.setVerticalGroup(
            jPnlCMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlCMHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlCMHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLbMaxMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbClose1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLbHide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPnlBg.add(jPnlCMH, java.awt.BorderLayout.PAGE_START);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        jPnlBg.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPnlBg, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLbClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbClose1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLbClose1MouseClicked

    private void jLbMaxMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbMaxMinMouseClicked

        if (state) {
            this.setExtendedState(NORMAL);
            state = false;
        } else {
            this.setExtendedState(MAXIMIZED_BOTH);
            state = true;
        }
    }//GEN-LAST:event_jLbMaxMinMouseClicked

    private void jLbHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLbHideMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLbHideMouseClicked

    private void jPnlCMHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlCMHMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPnlCMHMousePressed

    private void jPnlCMHMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlCMHMouseDragged
        Point point = MouseInfo.getPointerInfo().getLocation();
        setLocation(point.x - x, point.y - y);
    }//GEN-LAST:event_jPnlCMHMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLbAccounting;
    private javax.swing.JLabel jLbAccountingIcon;
    private javax.swing.JLabel jLbClose1;
    private javax.swing.JLabel jLbCurtomers;
    private javax.swing.JLabel jLbCustomersIcon;
    private javax.swing.JLabel jLbDrinks;
    private javax.swing.JLabel jLbDrinksIcon;
    private javax.swing.JLabel jLbFoodDishes;
    private javax.swing.JLabel jLbFoodDishesIcon;
    private javax.swing.JLabel jLbHide;
    private javax.swing.JLabel jLbHomePage;
    private javax.swing.JLabel jLbHomePageIcono;
    private javax.swing.JLabel jLbLogOut;
    private javax.swing.JLabel jLbMaxMin;
    private javax.swing.JLabel jLbMenus;
    private javax.swing.JLabel jLbMenusIcon;
    private javax.swing.JLabel jLbRestaurant;
    private javax.swing.JLabel jLbRestaurantIcon;
    private javax.swing.JLabel jLbUserName;
    private javax.swing.JLabel jLbUserPhoto;
    private javax.swing.JLabel jLbUsers;
    private javax.swing.JLabel jLbUsersIcon;
    private javax.swing.JPanel jPnlAccounting;
    private javax.swing.JPanel jPnlBg;
    private javax.swing.JPanel jPnlCMH;
    private javax.swing.JPanel jPnlCustomers;
    private javax.swing.JPanel jPnlDrinks;
    private javax.swing.JPanel jPnlFoodDishes;
    private javax.swing.JPanel jPnlHomePage;
    private javax.swing.JPanel jPnlMenus;
    private javax.swing.JPanel jPnlRestaurant;
    private javax.swing.JPanel jPnlSide;
    private javax.swing.JPanel jPnlUsers;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    private void addIcon(JLabel lb, String pathIcon) {
        ImageIcon img = new ImageIcon(pathIcon);
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(
                lb.getWidth(),
                lb.getHeight(),
                Image.SCALE_DEFAULT));
        lb.setIcon(icono);
        this.repaint();
    }
}
